encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'enc'

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.page, name='page'), 
    path("search/", views.search, name='search'),
    path("create_page/", views.create_page, name="create"),
    path("wiki/<str:title>/edit/", views.edit, name="edit"),
    path("random/", views.random_page, name="random"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown
from django.shortcuts import render
from . import util
from django import forms
import random, re

class NewPageForm(forms.Form):
    Title = forms.CharField(label="Название")
    Text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 5}))

class EditPageForm(forms.Form):
    Title = forms.CharField(label="Название", widget=forms.TextInput(attrs={'readonly':'readonly'}))
    Text = forms.CharField(widget=forms.Textarea(attrs={'rows': 10, 'cols': 5}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def page(requests, title):
    text = util.get_entry(title)
    if text is not None:
        md = markdown.Markdown()
        result = md.convert(text)
        return render(requests, "encyclopedia/page.html", {
            "content": result,
            "title": title
        })
    else:
        return render(requests, "encyclopedia/page.html", {
            "content": "<h2> Статья не найдена 1 </h2>"
        })

def search(requests):
    enc_list = []
    if requests.method == "POST":
        form = requests.POST
    wiki_list = util.list_entries()
    wiki_list_lower = []
    for wiki in wiki_list:
        wiki_list_lower.append(wiki.lower())
    if form['q'].lower() in wiki_list_lower:
        return page(requests, form['q'])
    elif wiki in wiki_list:
        for wiki in wiki_list:
            wiki_lower = wiki.lower()
            if wiki_lower.find(form['q'].lower()) != -1:
                enc_list.append(wiki)
        return render(requests, "encyclopedia/search.html", {
            "contents": enc_list
        })

    else:
        return render(requests, "encyclopedia/search.html")


def create_page(requests):
    entries_list = util.list_entries()
    if requests.method == "POST":
        form = NewPageForm(requests.POST)
        if form.is_valid():
            Title = form.cleaned_data["Title"]
            Text = form.cleaned_data["Text"]
            if Title not in entries_list:
                util.save_entry(Title, f"#{Title} \n {Text}")
                return page(requests, Title)
            else:
                form.add_error('Title', 'Ошибка, статья с таким именем уже существует!')
                return render(requests, "encyclopedia/create_new.html", {
                    "form": form
                })
    return render(requests, "encyclopedia/create_new.html", {
        "form": NewPageForm()
    })

def edit(requests, title):
    text = util.get_entry(title)
    if requests.method == "POST":
        form = requests.POST
        print(form)
        Text = form['text']
        md = markdown.Markdown()
        text = md.convert(Text)
        util.save_entry(title, f"#{title} \n {text}")
        return page(requests, title)
    else:
        md = markdown.Markdown()
        result = md.convert(text)
        return render(requests, "encyclopedia/edit.html", {
             "title": title,
             "text": result.split('</h1>')[1].replace("<p>",'').replace("</p>", '')
        })

def random_page(requests):
    return page(requests, random.choice(util.list_entries()))

encyclopedia/templates/encyclopedia/create_new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h3> Введите название и текст для новой статьи </h3>
    <form action="{% url 'enc:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <p><input type="submit"></p>
    </form>
<p><a href="{% url 'enc:index' %}"> Вернуться на главную страницу </a></p>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h3> Редактор текста: </h3>
    <form action="" method="post">
        {% csrf_token %}
        <h1> {{title}} </h1>

        <textarea name="text"> {{text}}  </textarea>

        <p><input type="submit"></p>
    </form>
<p><a href="{% url 'enc:index' %}"> Вернуться на главную страницу </a></p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="wiki/{{entry|safe}}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action=" {%url 'enc:search'%}" method="post">
                     {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'enc:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'enc:create'%}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'enc:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
             </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {{ content|safe }}

<p><a href="{% url 'enc:edit' title%}"> Редактировать </a></p>

<p><a href="{% url 'enc:index' %}"> Содержание </a></p>


{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h2> Результат поиска: </h2>
    <ul>
        {% if contents|length %}
        {% for content in contents%}
             <li><a href="/wiki/{{content}}">{{ content }}</a></li>
        {% endfor %}
        {% else %}
        <li> Стараница не найдена </li>
        {% endif %}
    </ul>
    <p><a href="{% url 'enc:index' %}"> Вернуться на главную страницу </a></p>
{% endblock %}